export enum AccountStatus {
  ACTIVE = "ACTIVE",
  DORMANT = "DORMANT",
  SUSPENDED = "SUSPENDED",
}

export enum AccountType {
  CORPORATE_CURRENT = "CORPORATE_CURRENT",
  CORPORATE_DOMICILIARY = "CORPORATE_DOMICILIARY",
  CORPORATE_SAVINGS = "CORPORATE_SAVINGS",
  INDIVIDUAL_CURRENT = "INDIVIDUAL_CURRENT",
  INDIVIDUAL_DOMICILIARY = "INDIVIDUAL_DOMICILIARY",
  INDIVIDUAL_SAVINGS = "INDIVIDUAL_SAVINGS",
  GROUP_CURRENT = "GROUP_CURRENT",
  GROUP_SAVINGS = "GROUP_SAVINGS",
  JOINT_CURRENT = "JOINT_CURRENT",
  JOINT_SAVINGS = "JOINT_SAVINGS",
}

export enum AccountCurrency {
  NGN = "NGN",
  USD = "USD",
  EUR = "EUR",
  GBP = "GBP",
  JPY = "JPY",
  AUD = "AUD",
  CAD = "CAD",
  CHF = "CHF",
  CNY = "CNY",
}
